$ACA0#hackMethodAddressTable#
$AD00#executeHack#
$AD20#cleanupZeroPage#
$AD30#initializePriceQuantity#
$AD50#changeQuantity#
$AD56#@return#
$AD68#@increment#
$AD7A#@apply#
$AD72#@decrement#
$BF90#calculateTotal#
$BFA0#@shift#
$BFAD#@skip#
$BFB6#@calculateBCD#
$BFC0#@loop#
$BFCE#@highNibble#
$BFD9#@lowNibble#
$BFC2#@highNibble#
$BFCD#@lowNibble#
